language:
  python

sudo:
  false

python:
  - "2.6"
  - "2.7"
  # - "3.2"  because of pep3134
  - "3.3"
  - "3.4"
  - "pypy"
  - "pypy3"

install:
  - pip install --use-mirrors -r requirements/package.txt -r requirements/test.txt
  - pip install coveralls

script:
  - py.test --cov isitbullshit test_isitbullshit.py

after_success:
  coveralls

notifications:
  email:
    - nineseconds@yandex.ru

matrix:
  allow_failures:
    - python: "pypy3"  # because of pep3134
